export const FORM_NEWPROJECT = "FORM_NEWPROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const FORM_VALIDATION = "FORM_VALIDATION";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";

export const GET_TASKS = "GET_TASKS";
export const ADD_TASK = "ADD_TASK";
export const TASK_VALIDATION = "TASK_VALIDATION";
export const REMOVE_TASK = "REMOVE_TASK";
export const TASK_STATE = "TASK_STATE";
